### ISSUE TITLE
FileCopyOperation unknown parameter

### ISSUE THREAD

**Issue by delanym** [jenkinsci/file-operations-plugin#129] opened 2024-09-13 21:36 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
println("Jenkins: ${Jenkins.instance.getVersion()}")
println("OS: ${System.getProperty('os.name')} - ${System.getProperty('os.version')}")
println("Java: ${System.getProperty('java.version')} - ${System.getProperty('java.vm.vendor')} (${System.getProperty('java.vm.name')})")
println "---"

Jenkins.instance.pluginManager.plugins
  .collect()
  .sort { it.getShortName() }
  .each {
    plugin -> println("${plugin.getShortName()}:${plugin.getVersion()}")
  }
return
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows server 2016

### Reproduction steps

Add a file copy operation to your Jenkinsfile
```
        fileOperations([
            fileCopyOperation(sourceFiles: 'build/target/*.zip', targetLocation: 'z:/release/distributions/')
        ])
```

### Expected Results

Copies file without error

### Actual Results

22:45:11  WARNING: Unknown parameter(s) found for class type 'sp.sd.fileoperations.FileCopyOperation': sourceFiles
22:45:11  File Copy Operation:
22:45:11  FATAL: Cannot invoke "String.startsWith(String)" because "rel" is null
22:45:11  Cannot invoke "String.startsWith(String)" because "rel" is null
22:45:11  FATAL: Cannot invoke "String.startsWith(String)" because "rel" is null

**Comment by jonesbusy** [comment] 2024-11-19 13:14
Duplicate of https://github.com/jenkinsci/file-operations-plugin/issues/143

Possible cause is a workflow plugin issue ?

This work well with freestyle

![Image](https://github.com/user-attachments/assets/ba19122e-e788-4d63-96a5-f087213b32f9)
![Image](https://github.com/user-attachments/assets/7f22edf1-92b3-4b42-97e5-b97661b300b7)

**Closed by jonesbusy** 2024-11-19 13:14 UTC
Labels: bug
